version: '3'
services:
  app:
    image: mittal394/demo-app:${TAG:-latest}
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
    deploy:
      replicas: 2
      mode: replicated
      endpoint_mode: vip